#!/usr/bin/env bash
# Regenerate every derived AI-instruction file from AGENTS.md.
#
# Deterministic: identical output on every run and every machine, so the
# pre-commit / CI drift check (--check) can fail the build on any difference.
# See CAPSIZE_PROJECT_STANDARDS.md §12.4 and §12.6.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

check_only=false
if [[ "${1:-}" == "--check" ]]; then
  check_only=true
fi

drift=0

# write <path> — reads the desired content from stdin. Leaves the file
# untouched (and reports drift under --check) when it already matches.
write() {
  local path="$1"
  mkdir -p "$(dirname "$path")"
  local tmp
  tmp="$(mktemp)"
  cat > "$tmp"
  if [[ -f "$path" ]] && cmp -s "$tmp" "$path"; then
    rm -f "$tmp"
    return 0
  fi
  if $check_only; then
    echo "drift: $path" >&2
    rm -f "$tmp"
    drift=1
    return 0
  fi
  mv "$tmp" "$path"
  echo "wrote: $path"
}

# The canonical source is AGENTS.md; every other file points at it.
write CLAUDE.md <<'EOF'
See [AGENTS.md](AGENTS.md). This file is generated by `scripts/sync-rules.sh`; do not edit.
EOF

write .github/copilot-instructions.md <<'EOF'
See [AGENTS.md](../AGENTS.md). This file is generated by `scripts/sync-rules.sh`; do not edit.
EOF

write .roo/rules/rules.md <<'EOF'
See [AGENTS.md](../../AGENTS.md). This file is generated by `scripts/sync-rules.sh`; do not edit.
EOF

write .cursor/rules/capsize-commons.mdc <<'EOF'
---
description: capsize-commons repository rules (generated shim)
alwaysApply: true
---

See [AGENTS.md](../../AGENTS.md). This file is generated by `scripts/sync-rules.sh`; do not edit.
EOF

if $check_only && [[ "$drift" -ne 0 ]]; then
  echo "Derived instruction files are out of date; run 'just sync-rules'." >&2
  exit 1
fi

exit 0
